### ISSUE TITLE
crash！！！

### ISSUE THREAD

**Issue by ShanShuWu** [Aikoyori/BocchiTheBlock-Fabric#2]
The mod crashed, using version 0.2.0 of the mod, the game cannot be started properly, the game version is 1.19.2, fabric0.14.11, fabric api 0.67.1

**Comment by Aikoyori** [comment]
May I have the crash report?

**Comment by Lancercmd** [comment]
> May I have the crash report?

fabric-loader-0.14.11-1.19.2
```]
# ../mods/
bocchitheblock_1.19.2-0.2.0.jar
fabric-api-0.69.0+1.19.2.jar
```
```
Time: 2022-12-17 22:37:43
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'bocchitheblock'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: com/llamalad7/mixinextras/MixinExtrasBootstrap
	at xyz.aikoyori.bocchitheblock.BocchiMod.onInitialize(BocchiMod.java:34)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more
Caused by: java.lang.ClassNotFoundException: com.llamalad7.mixinextras.MixinExtrasBootstrap
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 10 more
```

**Comment by Aikoyori** [comment]
I think I'll have to update Fabric API on my end :/ will do that once I got around to add Nijika block as well

EDIT: I got the same crash using it on Fabric. Thanks for the heads up
